#!/usr/bin/env python3
"""Generate lib/StaTeX/statex_symbols.gen.cpp from tools/genfont/symbols.tsv.

The parser looks a command name up in this table; layout then asks the glyph
store for the codepoint the table gave. So the table and the atlas are two
halves of one fact, and when they disagree the failure is quiet and late: the
name parses, and layout refuses with MissingGlyph at a different stage and with
a different error from the UnknownCommand you would expect.

Generating both from symbols.tsv is what keeps them in step, and --check-atlas
turns the remaining gap into a build error rather than a rendering surprise.

    python tools/genfont/mksymtable.py
    python tools/genfont/mksymtable.py --check-atlas lib/glyphstore/statex_glyphs.gen.cpp
"""

from __future__ import annotations

import argparse
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, "..", ".."))
SYMBOLS_TSV = os.path.join(HERE, "symbols.tsv")
DEFAULT_OUT = os.path.join(REPO, "lib", "StaTeX", "statex_symbols.gen.cpp")

# statex_parser.cpp builds the lookup key in `char key[32]`, so a longer name
# is rejected as UnknownCommand before it ever reaches the table.
MAX_NAME = 31

SYMBOL_FACE = 3

PREAMBLE = '''// GENERATED by tools/genfont/mksymtable.py from tools/genfont/symbols.tsv.
// Do not edit: change the table and regenerate.
//
// Sorted by name (ASCII), which findSymbol's binary search requires
// (STX-RES-01). The generator guarantees the order and test_symbols.cpp sweeps
// every entry to confirm each name finds itself.
#include "statex_glyphstore.h"  // STATEX_FLASH
#include "statex_symbols.h"

namespace statex {
namespace {

// STATEX_FLASH for the same reason the glyph atlas has it: this target's
// linker script copies plain .rodata into DTCM, and at ~600 entries the table
// is 7 KB of RAM that never changes. The name strings it points at are
// separate literals and still land in .rodata -- worth a flash string pool if
// DTCM ever gets tight.
const SymbolEntry kSymbols[] STATEX_FLASH = {
'''

EPILOGUE = '''};

constexpr int kCount = static_cast<int>(sizeof(kSymbols) / sizeof(kSymbols[0]));

// Compare a NUL-terminated entry name against the key slice key[0..len).
// Returns <0 if name<key, 0 if equal, >0 if name>key.
constexpr int cmpNameKey(const char* name, const char* key, int len) {
  int i = 0;
  for (; i < len; ++i) {
    const unsigned char cn = static_cast<unsigned char>(name[i]);
    if (cn == 0) return -1;  // name ran out first -> shorter -> less
    const unsigned char ck = static_cast<unsigned char>(key[i]);
    if (cn != ck) return (cn < ck) ? -1 : 1;
  }
  return (name[i] == '\\0') ? 0 : 1;  // name longer than key -> greater
}

// The ordering check cannot be a static_assert any more: kSymbols lives in a
// flash section and so is `const`, not `constexpr`, and a const array is not a
// constant expression. The generator emits the table sorted and
// test_symbols.cpp sweeps every entry to confirm each name finds itself, which
// is a stronger statement than sortedness and catches the same bug.
static_assert(kCount > 0, "the symbol table is empty");

}  // namespace

const SymbolEntry* findSymbol(const char* key, int len) {
  if (key == nullptr || len <= 0) return nullptr;
  int lo = 0;
  int hi = kCount - 1;
  while (lo <= hi) {
    const int mid = lo + (hi - lo) / 2;
    const int c = cmpNameKey(kSymbols[mid].name, key, len);
    if (c == 0) return &kSymbols[mid];
    if (c < 0) {
      lo = mid + 1;
    } else {
      hi = mid - 1;
    }
  }
  return nullptr;
}

int symbolCount() { return kCount; }

const SymbolEntry* symbolAt(int i) {
  if (i < 0 || i >= kCount) return nullptr;
  return &kSymbols[i];
}

}  // namespace statex
'''


def load_rows(path: str) -> list:
    rows = []
    with io.open(path, encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("#") or line.startswith("name\t"):
                continue
            f = line.rstrip("\n").split("\t")
            if len(f) < 10:
                continue
            rows.append(dict(name=f[0], cp=int(f[1], 16), atom=f[3],
                             limits=f[4] == "1", face=int(f[6])))
    return rows


def atlas_codepoints(path: str) -> set:
    """(face, codepoint) of every base record in a generated atlas."""
    text = io.open(path, encoding="utf-8", errors="replace").read()
    m = re.search(r"const GlyphRecord kGlyphs\[\][^=]*=\s*\{(.*?)\n\};",
                  text, re.S)
    if m is None:
        raise SystemExit("%s: no kGlyphs table found" % path)
    out = set()
    for row in re.finditer(r"\{([^{}]*)\}", m.group(1)):
        v = [x.strip() for x in row.group(1).split(",")]
        # face, sdfW, sdfH, variant, codepoint, ...
        if int(v[3], 0) == 0:
            out.add((int(v[0], 0), int(v[4], 0)))
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tsv", default=SYMBOLS_TSV)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--check-atlas",
                    help="a generated statex_glyphs.gen.cpp; every symbol's "
                         "codepoint must have a base record in it")
    args = ap.parse_args()

    rows = load_rows(args.tsv)
    if not rows:
        raise SystemExit("%s holds no symbols" % args.tsv)

    long_names = [r["name"] for r in rows if len(r["name"]) > MAX_NAME]
    if long_names:
        raise SystemExit(
            "these names are longer than the parser's %d-character key buffer "
            "and could never be matched: %s" % (MAX_NAME, ", ".join(long_names)))

    seen = {}
    for r in rows:
        if r["name"] in seen:
            raise SystemExit("duplicate symbol name %r" % r["name"])
        seen[r["name"]] = r

    if args.check_atlas:
        have = atlas_codepoints(args.check_atlas)
        missing = sorted((r["name"], r["cp"]) for r in rows
                         if (r["face"], r["cp"]) not in have)
        if missing:
            print("%d symbol(s) have no glyph in %s:"
                  % (len(missing), args.check_atlas), file=sys.stderr)
            for name, cp in missing[:20]:
                print("   %-22s U+%04X" % (name, cp), file=sys.stderr)
            if len(missing) > 20:
                print("   ... and %d more" % (len(missing) - 20), file=sys.stderr)
            raise SystemExit(
                "every name in the table must resolve to a glyph, or it parses "
                "and then fails in layout with MissingGlyph")
        print("atlas cross-check: all %d symbols have a glyph" % len(rows))

    rows.sort(key=lambda r: r["name"])
    # findSymbol binary-searches this table, so the order is load-bearing. The
    # C++ side can no longer assert it -- the table is const in a flash section
    # rather than constexpr, and a const array is not a constant expression --
    # so it is guaranteed here and swept at runtime by test_symbols.cpp, which
    # checks that every one of the 600 names finds itself.
    names = [r["name"] for r in rows]
    assert names == sorted(names), "emit order is not sorted by name"
    assert len(set(names)) == len(names), "duplicate names survived"

    body = "".join(
        '    {"%s", 0x%04X, AtomType::%s, %s},\n'
        % (r["name"], r["cp"], r["atom"], "true" if r["limits"] else "false")
        for r in rows)

    io.open(args.out, "w", encoding="utf-8", newline="\n").write(
        PREAMBLE + body + EPILOGUE)
    print("wrote %s (%d symbols, %s .. %s)"
          % (args.out, len(rows), rows[0]["name"], rows[-1]["name"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
